services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudacademy-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cloudacademy
      POSTGRES_USER: cloudacademy_user
      POSTGRES_PASSWORD: cloudacademy123

    ports:
      - "5432:5432"

    volumes:
      - cloudacademy_postgres_data:/var/lib/postgresql/data

volumes:
  cloudacademy_postgres_data: